INSERT INTO disciplina (codigo, nome, area) VALUES
                                                ('COM101', 'Algoritmos e Estruturas de Dados', 'Computação'),
                                                ('COM201', 'Programação Orientada a Objetos', 'Computação'),
                                                ('COM301', 'Arquitetura de Computadores', 'Computação'),
                                                ('COM401', 'Redes de Computadores', 'Computação'),
                                                ('COM501', 'Sistemas Operacionais', 'Computação'),
                                                ('COM601', 'Banco de Dados I', 'Computação'),
                                                ('COM701', 'Redes de Computadores II', 'Computação'),
                                                ('COM801', 'Sistemas Distribuídos', 'Computação'),
                                                ('COM901', 'Compiladores', 'Computação'),
                                                ('COM1002', 'Engenharia de Software II', 'Computação'),
                                                ('COM1101', 'Tópicos Especiais em Computação I', 'Computação'),
                                                ('COM1201', 'Tópicos Especiais em Computação II', 'Computação'),
                                                ('MAT101', 'Cálculo I', 'Matemática'),
                                                ('MAT201', 'Probabilidade e Estatística', 'Matemática'),
                                                ('MAT301', 'Cálculo II', 'Matemática'),
                                                ('FIS101', 'Física I', 'Física'),
                                                ('FIS201', 'Física II', 'Física'),
                                                ('COM302', 'Lógica de Programação', 'Computação'),
                                                ('COM402', 'Engenharia de Software', 'Computação'),
                                                ('COM502', 'Inteligência Artificial', 'Computação');